### ISSUE TITLE
found some bugs on big_o.py

### ISSUE THREAD

**Issue by joepartridge** [pberkes/big_O#12]
Unexpected dot on line: "from .complexities import ALL_CLASSES"
Missing: import datagen

With those minor fixes it works... with your examples.
Couldn't figure out how to make it work with other simple functions: selection sorting, bisection search, fibonacci, and others.
Could you please put some more examples on your README?

**Comment by pberkes** [comment]
Thanks for the report @joepartridge . I think you are using an old version of the library, since I cannot find those problems in the latest code: https://github.com/pberkes/big_O/blob/master/big_o/big_o.py

**Comment by pberkes** [comment]
I'm closing this issue, and opening a new one for the request of more examples
