### ISSUE TITLE
Add installation instructions to README

### ISSUE THREAD

**Issue by SHxKM** [pberkes/big_O#35]
The library title on Github is `big_O`, but one needs `pip install big-O` to install it. This ambiguity can be easily solved by including a short installation section to the README. I will try to do it later but in case someone wants to do it before then.

**Comment by Abdullah-Majid** [comment]
can I be assigned this?

**Comment by Abdullah-Majid** [comment]
<https://github.com/pberkes/big_O/pull/53>
